/*
 * serdfs/dos/src/genmsg.c
 * Adapted from vendor/etherdfs-baseline/etherdfs/trunk/genmsg.c
 * EtherDFS by Mateusz Viste, MIT licence. See COPYING and NOTICES.
 *
 * Changes from vendor:
 *   - Product name and usage string updated for SerialDFS.
 *   - Removed packet-driver messages (pktdfail, nosrvfnd, instlled MAC line,
 *     pktdrvat interrupt line).
 *   - Added comfail message for serial-port open failure.
 *   - All other message slots kept for compatibility with etherdfs.c structure.
 *
 * genmsg generates C files that contain inline assembly for outputting each
 * string SerialDFS might need to print.  The assembly uses INT 21h AH=09h
 * (print $-terminated string) with CS-relative addressing so the strings
 * survive after the transient segment is freed.
 */

#include <stdio.h>
#include "version.h"

int genmsg(char *fname, char *msg) {
  unsigned short i;
  FILE *fd;
  fd = fopen(fname, "wb");
  if (fd == NULL) return(1);
  fprintf(fd, "/* %s: THIS FILE IS AUTO-GENERATED BY GENMSG.C -- DO NOT MODIFY! */\r\n", fname);
  fprintf(fd, "_asm {\r\n");
  fprintf(fd, "  push ds\r\n");
  fprintf(fd, "  push dx\r\n");
  fprintf(fd, "  push ax\r\n");
  fprintf(fd, "  call getip");
  for (i = 0; msg[i] != 0; i++) {
    if ((i & 15) == 0) {
      fprintf(fd, "\r\n  S%03X db ", i >> 4);
    } else {
      fprintf(fd, ",");
    }
    fprintf(fd, "%u", msg[i]);
  }
  fprintf(fd, ",'$'\r\n");
  fprintf(fd, " getip:\r\n");
  fprintf(fd, "  pop dx\r\n");
  fprintf(fd, "  push cs\r\n");
  fprintf(fd, "  pop ds\r\n");
  fprintf(fd, "  mov ah,9h\r\n");
  fprintf(fd, "  int 21h\r\n");
  fprintf(fd, "  pop ax\r\n");
  fprintf(fd, "  pop dx\r\n");
  fprintf(fd, "  pop ds\r\n");
  fprintf(fd, "};\r\n");
  fclose(fd);
  return(0);
}

int main(void) {
  int r = 0;

  r += genmsg("msg\\help.c",
    "SerialDFS v" PVER " / Copyright (C) " PDATE "\r\n"
    "A network drive for DOS, running over RS-232 serial\r\n"
    "\r\n"
    "Usage: serdfs rdrv-ldrv [rdrv2-ldrv2 ...] /COMn /BAUD:rate [options]\r\n"
    "       serdfs /u\r\n"
    "\r\n"
    "Options:\r\n"
    "  /COM1       use COM1 (default)\r\n"
    "  /COM2       use COM2\r\n"
    "  /BAUD:N     baud rate (9600, 19200, 38400, 57600, 115200)\r\n"
    "  /STATUS     show status bar\r\n"
    "  /NOSTATUS   disable status bar (default)\r\n"
    "  /q          quiet mode\r\n"
    "  /u          unload SerialDFS from memory\r\n"
    "\r\n"
    "Example:  serdfs C-X /COM1 /BAUD:57600\r\n"
    );

  r += genmsg("msg\\unsupdos.c", "Unsupported DOS version! SerialDFS requires MS-DOS 5+.\r\n");

  r += genmsg("msg\\noredir.c", "Redirector installation has been forbidden either by DOS or another process.\r\n");

  r += genmsg("msg\\alrload.c", "SerialDFS is already installed and cannot be loaded twice.\r\n");

  r += genmsg("msg\\notload.c", "SerialDFS is not loaded, so it cannot be unloaded.\r\n");

  r += genmsg("msg\\tsrcomfa.c", "Communication with the TSR failed.\r\n");

  r += genmsg("msg\\nomultpx.c", "Failed to find an available INT 2F multiplex id.\r\nYou may have loaded too many TSRs already.\r\n");

  r += genmsg("msg\\othertsr.c", "SerialDFS cannot be unloaded because another TSR hooked its interrupt handler.\r\n");

  r += genmsg("msg\\unloaded.c", "SerialDFS unloaded successfully.\r\n");

  r += genmsg("msg\\mapfail.c",
    "Unable to activate the local drive mapping. You are either using an\r\n"
    "unsupported operating system, or your LASTDRIVE directive does not permit\r\n"
    "to define the requested drive letter (try LASTDRIVE=Z in your CONFIG.SYS).\r\n"
  );

  r += genmsg("msg\\drvactiv.c",
    "The requested local drive letter is already in use. Please choose another\r\n"
    "drive letter.\r\n"
  );

  r += genmsg("msg\\memfail.c", "Memory alloc error!\r\n");

  r += genmsg("msg\\relfail.c", "DS/SS relocation failed.\r\n");

  r += genmsg("msg\\comfail.c", "Serial port initialization failed. Check /COMn and /BAUD:N arguments.\r\n");

  r += genmsg("msg\\instlled.c", "SerialDFS v" PVER " installed (");

  if (r != 0) puts("genmsg: at least one error occurred when compiling messages");

  return(r);
}
