#!/usr/bin/env python3
"""
genmsg.py — Generate msg/*.c message files for the SerialDFS DOS build.
Python replacement for genmsg.c / GENMSG.EXE.
Run from dos/src/ or pass output dir as argv[1].
"""
import os, sys

PVER  = "1.0"
PDATE = "2026"

def genmsg(fname, msg):
    os.makedirs(os.path.dirname(fname) or '.', exist_ok=True)
    with open(fname, 'w', newline='\r\n') as f:
        bn = os.path.basename(fname)
        f.write(f'/* {bn}: THIS FILE IS AUTO-GENERATED BY GENMSG.PY -- DO NOT MODIFY! */\r\n')
        f.write('_asm {\r\n')
        f.write('  push ds\r\n')
        f.write('  push dx\r\n')
        f.write('  push ax\r\n')
        f.write('  call getip')
        byt = msg.encode('latin-1')
        for i, b in enumerate(byt):
            if (i & 15) == 0:
                f.write(f'\r\n  S{i >> 4:03X} db ')
            else:
                f.write(',')
            f.write(str(b))
        f.write(",'$'\r\n")
        f.write(' getip:\r\n')
        f.write('  pop dx\r\n')
        f.write('  push cs\r\n')
        f.write('  pop ds\r\n')
        f.write('  mov ah,9h\r\n')
        f.write('  int 21h\r\n')
        f.write('  pop ax\r\n')
        f.write('  pop dx\r\n')
        f.write('  pop ds\r\n')
        f.write('};\r\n')

outdir = sys.argv[1] if len(sys.argv) > 1 else 'msg'

genmsg(f'{outdir}/help.c',
    f'SerialDFS v{PVER} / Copyright (C) {PDATE}\r\n'
    'A network drive for DOS, running over RS-232 serial\r\n'
    '\r\n'
    'Usage: serdfs rdrv-ldrv [rdrv2-ldrv2 ...] /COMn /BAUD:rate [options]\r\n'
    '       serdfs /u\r\n'
    '\r\n'
    'Options:\r\n'
    '  /COM1       use COM1 (default)\r\n'
    '  /COM2       use COM2\r\n'
    '  /BAUD:N     baud rate (9600, 19200, 38400, 57600, 115200)\r\n'
    '  /STATUS     show status bar\r\n'
    '  /NOSTATUS   disable status bar (default)\r\n'
    '  /q          quiet mode\r\n'
    '  /u          unload SerialDFS from memory\r\n'
    '\r\n'
    'Example:  serdfs C-X /COM1 /BAUD:57600\r\n'
)

genmsg(f'{outdir}/unsupdos.c',
    'Unsupported DOS version! SerialDFS requires MS-DOS 5+.\r\n')

genmsg(f'{outdir}/noredir.c',
    'Redirector installation has been forbidden either by DOS or another process.\r\n')

genmsg(f'{outdir}/alrload.c',
    'SerialDFS is already installed and cannot be loaded twice.\r\n')

genmsg(f'{outdir}/notload.c',
    'SerialDFS is not loaded, so it cannot be unloaded.\r\n')

genmsg(f'{outdir}/tsrcomfa.c',
    'Communication with the TSR failed.\r\n')

genmsg(f'{outdir}/nomultpx.c',
    'Failed to find an available INT 2F multiplex id.\r\n'
    'You may have loaded too many TSRs already.\r\n')

genmsg(f'{outdir}/othertsr.c',
    'SerialDFS cannot be unloaded because another TSR hooked its interrupt handler.\r\n')

genmsg(f'{outdir}/unloaded.c',
    'SerialDFS unloaded successfully.\r\n')

genmsg(f'{outdir}/mapfail.c',
    'Unable to activate the local drive mapping. You are either using an\r\n'
    'unsupported operating system, or your LASTDRIVE directive does not permit\r\n'
    'to define the requested drive letter (try LASTDRIVE=Z in your CONFIG.SYS).\r\n')

genmsg(f'{outdir}/drvactiv.c',
    'The requested local drive letter is already in use. Please choose another\r\n'
    'drive letter.\r\n')

genmsg(f'{outdir}/memfail.c', 'Memory alloc error!\r\n')

genmsg(f'{outdir}/relfail.c', 'DS/SS relocation failed.\r\n')

genmsg(f'{outdir}/comfail.c',
    'Serial port initialization failed. Check /COMn and /BAUD:N arguments.\r\n')

genmsg(f'{outdir}/instlled.c', f'SerialDFS v{PVER} installed (')

print(f'Generated {len(os.listdir(outdir))} message files in {outdir}/')
