/* comfail.c: THIS FILE IS AUTO-GENERATED BY GENMSG.PY -- DO NOT MODIFY! */
_asm {
  push ds
  push dx
  push ax
  call getip
  S000 db 83,101,114,105,97,108,32,112,111,114,116,32,105,110,105,116
  S001 db 105,97,108,105,122,97,116,105,111,110,32,102,97,105,108,101
  S002 db 100,46,32,67,104,101,99,107,32,47,67,79,77,110,32,97
  S003 db 110,100,32,47,66,65,85,68,58,78,32,97,114,103,117,109
  S004 db 101,110,116,115,46,13,10,'$'
 getip:
  pop dx
  push cs
  pop ds
  mov ah,9h
  int 21h
  pop ax
  pop dx
  pop ds
};
