/* instlled.c: THIS FILE IS AUTO-GENERATED BY GENMSG.PY -- DO NOT MODIFY! */
_asm {
  push ds
  push dx
  push ax
  call getip
  S000 db 83,101,114,105,97,108,68,70,83,32,118,49,46,48,32,105
  S001 db 110,115,116,97,108,108,101,100,32,40,'$'
 getip:
  pop dx
  push cs
  pop ds
  mov ah,9h
  int 21h
  pop ax
  pop dx
  pop ds
};
