/* notload.c: THIS FILE IS AUTO-GENERATED BY GENMSG.PY -- DO NOT MODIFY! */
_asm {
  push ds
  push dx
  push ax
  call getip
  S000 db 83,101,114,105,97,108,68,70,83,32,105,115,32,110,111,116
  S001 db 32,108,111,97,100,101,100,44,32,115,111,32,105,116,32,99
  S002 db 97,110,110,111,116,32,98,101,32,117,110,108,111,97,100,101
  S003 db 100,46,13,10,'$'
 getip:
  pop dx
  push cs
  pop ds
  mov ah,9h
  int 21h
  pop ax
  pop dx
  pop ds
};
