/* unloaded.c: THIS FILE IS AUTO-GENERATED BY GENMSG.PY -- DO NOT MODIFY! */
_asm {
  push ds
  push dx
  push ax
  call getip
  S000 db 83,101,114,105,97,108,68,70,83,32,117,110,108,111,97,100
  S001 db 101,100,32,115,117,99,99,101,115,115,102,117,108,108,121,46
  S002 db 13,10,'$'
 getip:
  pop dx
  push cs
  pop ds
  mov ah,9h
  int 21h
  pop ax
  pop dx
  pop ds
};
